### ISSUE TITLE
Windows: panic: dial unix: missing address with ssh pass

### ISSUE THREAD

**Issue by loom7** [kevinconway/remouseable#12]
Hey, i have the same problem, but using a ssh-password on windows:
(Worked once, then i closed the cmd nad then it showed this, also after reboot of the tablet and the pc)

```
remouseable.exe --ssh-ip="192.168.254.61:22 --ssh-password="therootpassword"
panic: dial unix: missing address

goroutine 1 [running]:
main.main()
        /home/travis/gopath/src/github.com/kevinconway/remouseable/main.go:68 +0x135d
```
or
```
remouseable0.4.exe --ssh-ip="192.168.254.61:22 --ssh-password="therootpassword"
panic: dial unix: missing address

goroutine 1 [running]:
main.main()
        C:/Users/kc/code/kevinconway/remouseable/main.go:71 +0x1fc5`
```
with ver. 0.4

**Edit: IP and Pass is right, also sharing the same wlan, but it can't connect. Using usb, it works. So the error message is always coming, when it is not finding the tablet?**

**Comment by kevinconway** [comment]
The only code path that results in a dial of a unix socket is when the password flag is not given or is given as an empty string like `--ssh-password=""`. Are the commands you put in the issue direct copy/paste? If so then the error may be due to a typo in the flags. 

`remouseable0.4.exe --ssh-ip="192.168.254.61:22 --ssh-password="therootpassword"` is missing a `"` at the end of the `--ssh-ip` flag. It should be `remouseable0.4.exe --ssh-ip="192.168.254.61:22" --ssh-password="therootpassword"` or it will consume `--ssh-password=` as part of the IP address which would subsequently set the password to nothing. The SSH agent setup, which includes the unix socket dial, happens before dialing the SSH IP so you'd end up seeing a `dial unix` error rather than an error dialing `192.168.254.61:22 --ssh-password=`. The only thing that makes me doubt this is the case is that there is an odd number of quotes in the command you posted which should result in the terminal waiting for more input instead of executing the command. The typo condition would only happen if either the `--ssh-password` flag was also missing a closing quote or if there's an extraneous quote character somewhere else.

**Comment by kevinconway** [comment]
If you're still seeing this error then feel free to re-open the issue. I'm closing it out assuming my suggestion helped.
