### ISSUE TITLE
public key based ssh still needs a password?

### ISSUE THREAD

**Issue by slartibart70** [kevinconway/remouseable#24]
Hi
i'm using my remarkable2 on a fixed IP address with public/private keypair login and without an additional password on the private ssh key. So `ssh remarkable` just connects to my device without any further ado...

If i am using remousable, then i need to specify an additional password like so:
`./remousable --event-file /dev/input/event1 --ssh-ip="192.168.3.30:22" --ssh-user="root" --ssh-password="secret" --orientation="right" --screen-height=1440 --screen-width=2560 --pressure-threshold=300`

which is... not really needed (see above, pub/priv keypair is setup properly)

Without the ssh-password parameter, i get the error message
`Enter Password: panic: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

Any idea how to fix this? (am i missing something?)

(and maybe add a 'cosmetic' fix: if the user does not specify a port with the param ssh-ip, just assume portnumber 22 instead of insisting to specify a port?
Error message reads:
`panic: dial tcp: address 192.168.3.30: missing port in address`)

**Comment by kevinconway** [comment]
You're looking for this setup: https://github.com/kevinconway/remouseable#advanced-ssh-setup. My best guess is that you have not yet registered your key pair with the ssh-agent on your machine. If you don't include the `--ssh-password` flag then the tool connects to your ssh-agent to handle the key exchange so it needs to know which keys are available for use. It's set up this way because going through the ssh-agent offers an easy integration will all kinds of SSH auth like using gpg-agent or integration with 2FA devices. If you want to use only a key-pair without the ssh-agent then I've outlined the changes I think are required to make that happen here: https://github.com/kevinconway/remouseable/issues/10#issuecomment-796287415.

A side note: The output you posted is a bit confusing to me. `Enter Password: ` only appears if you've set the `--ssh-password` flag to `-`. If you leave the flag out entirely then the SSH setup will attempt to the ssh-agent. Your error output appears to show both code paths active which is only possible if you set `--ssh-password="-"` and then hit enter when prompted without typing anything. It doesn't hurt anything to do that but I'd recommend leaving out the flag entirely.

**Comment by kevinconway** [comment]
I'm going to close this issue assuming the setup I linked helped out. Feel free to re-open the issue if you still think there's a bug.

**Comment by slartibart70** [comment]
yes, thank you for the info!
I will get my hands dirty with go... after reading a bit about go programming.
At the moment, i just don't use ssh-agent (never had the need for it)
